title: Openbracket
logo: /assets/img/ob_logo.png
description: TJ Gillis - Game Dev / DevOps / App Dev
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
mastodon: http://mastodon.openbracket.ca
blog: http://blog.openbracket.ca
github: http://github.com/bardic
