title: Openbracket
logo: /assets/img/ob_logo.png
description: TJ Gillis - Game Dev / DevOps / App Dev
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
mastodon: mastodon.openbracket.ca
blog: blog.openbracket.ca
github: github.com/bardic
